baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true